# A name for your workflow
name: Node.js CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ] # Runs on pushes to the main branch
  pull_request:
    branches: [ "main" ] # Runs on pull requests targeting the main branch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      # Sets up the Node.js environment
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Installs project dependencies
      - name: Install dependencies
        run: npm install

      # Runs your linter
      - name: Run linter
        run: npm run lint

      # Runs your tests
      - name: Run tests
        run: npm test
